---
title: "Untitled"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(p8105.datasets)
library(plotly)
```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
instacart %>%
  janitor::clean_names()%>%
  group_by(aisle_id)%>%
  summarise(n = n())%>%
  filter(n < 100000)%>%
  plot_ly(x= ~aisle_id, y = ~n)
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
instacart %>%
  janitor::clean_names() %>%
  filter(
    department == "produce"
  )%>%
  group_by(aisle) %>%
  summarise(
    n_sum = n()
  ) %>%
  mutate(aisle=fct_reorder(aisle,n_sum)) %>%
   plot_ly(x = ~aisle, y = ~n_sum, color = ~aisle, type = "bar")
```

### Chart C

```{r}
instacart %>%
  janitor::clean_names()%>%
  filter(
    department == "produce")%>%
  group_by(aisle)%>%
  select(aisle, days_since_prior_order)%>%
  plot_ly(y = ~days_since_prior_order,  type = "box", color = ~aisle)
```

